---
development:
  dialect: "sqlite3"
  database: /home/william/programming/golang/src/github.com/Burmudar/gomodoro_gomodoro_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/william/programming/golang/src/github.com/Burmudar/gomodoro_gomodoro_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/william/programming/golang/src/github.com/Burmudar/gomodoro_gomodoro_production.sqlite
