---
development:
  dialect: "sqlite3"
  database: /home/wbezuide/programming/golang/src/github.com/burmudar/gomodoro_gomodoro_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/wbezuide/programming/golang/src/github.com/burmudar/gomodoro_gomodoro_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/wbezuide/programming/golang/src/github.com/burmudar/gomodoro_gomodoro_production.sqlite
